services:
  mysql:
    image: mysql:8.0
    container_name: campuseats-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: campuseats_prod
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - campuseats-networks
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-u","root","-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s


  redis:
    image: redis:7.0
    container_name: campuseats-redis
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - campuseats-networks

  backend:
    image: gigglen/campuseats-backend:latest
    container_name: campuseats-backend
    env_file:
      - .env.prod
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    networks:
      - campuseats-networks

  customer-app:
    image: gigglen/campuseats-customer-app:latest
    container_name: campuseats-customer-app
    restart: always
    networks:
      - campuseats-networks

  console-app:
    image: gigglen/campuseats-console-app:latest
    container_name: campuseats-console-app
    restart: always
    networks:
      - campuseats-networks


  nginx:
    image: nginx:latest
    container_name: campuseats-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/campuseats.conf:/etc/nginx/conf.d/campuseats.conf:ro
    restart: always
    networks:
      - campuseats-networks
    depends_on:
      - backend
      - customer-app


volumes:
  mysql_data:
  redis_data:

networks:
  campuseats-networks:
    driver: bridge