@host = http://localhost:8090

### PART 1: Sad paths
### P1: Invalid email format - 400
POST {{host}}/api/v1/auth/send-code?email=not-an-email

### P2: Registering without ever receiving a verification code - 400
POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
  "name": "Ghost",
  "email": "never.requested@example.com",
  "password": "ghost123",
  "address": "123 UCD",
  "phoneNumber": "0871234567",
  "roles": ["ROLE_STUDENT"],
  "verificationCode": "123456"
}

### P3: Invalid verification code format
POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
  "name": "Blair",
  "email": "{{studentEmail}}",
  "password": "blair123",
  "address": "123 UCD",
  "phoneNumber": "0871234567",
  "roles": ["ROLE_STUDENT"],
  "verificationCode": "abc"
}

### PART 2: Student Registration Process

### S1:Send verification code-200
### After require the verification code, save code into env from target test email
POST {{host}}/api/v1/auth/send-code?email=yuhan.wang4%2Bstudent@ucdconnect.ie

### S2: Sad path - Repeated requests within 60 seconds → 429
POST {{host}}/api/v1/auth/send-code?email=yuhan.wang4%2Bstudent@ucdconnect.ie

### S3: Sad path - A verification code with correct format but incorrect content → 400
POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
  "name": "Blair",
  "email": "{{studentEmail}}",
  "password": "blair123",
  "address": "123 UCD",
  "phoneNumber": "0871234567",
  "roles": ["ROLE_STUDENT"],
  "verificationCode": "000000"
}

### S4.Register STUDENT user - happy path
POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
  "name": "Blair",
  "email": "{{studentEmail}}",
  "password": "blair123",
  "address": "123 UCD",
  "phoneNumber": "0871234567",
  "roles": ["ROLE_STUDENT"],
  "verificationCode": "249513"
}

### S5: Send code failure - The registered email address requests a verification code again → 409
POST {{host}}/api/v1/auth/send-code?email=yuhan.wang4%2Bstudent@ucdconnect.ie

### S6: Register failure - sad path - existed email-> 409
POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
  "name": "Nini",
  "email": "{{studentEmail}}",
  "password": "nini123",
  "address": "123 UCD campus",
  "phoneNumber": "0871234567",
  "roles": ["ROLE_STUDENT"],
  "verificationCode": "{{verificationCode}}"
}

### PART 3: ADMIN user Registration Process
### A1: Send code to ADMIN user - HAPPY PATH
POST {{host}}/api/v1/auth/send-code?email=yuhan.wang4%2Badmin@ucdconnect.ie

### A2: Register ADMIN user - HAPPY PATH
POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
  "name": "admin_test",
  "email": "{{adminEmail}}",
  "password": "admin123",
  "address": "123 UCD",
  "phoneNumber": "0871234567",
  "roles": ["ROLE_ADMIN"],
  "verificationCode": "298742"
}

### PART 4: MANAGER user Registration Process
### M1: Send code to MANAGER user - HAPPY PATH
POST {{host}}/api/v1/auth/send-code?email=yuhan.wang4%2Bmanager@ucdconnect.ie

### M2: Register MANAGER user
POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
  "name": "manager_test",
  "email": "{{managerEmail}}",
  "password": "manager123",
  "address": "123 UCD",
  "phoneNumber": "0871234567",
  "roles": ["ROLE_MANAGER"],
  "verificationCode": "914194"
}


### 3.Login- Happy path - set users token
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "{{studentEmail}}",
  "password": "student123"
}
> {%
    client.log("Full response: " + JSON.stringify(response.body));
    client.log("data field: " + JSON.stringify(response.body.data));
    client.global.set("accessToken",response.body.data.accessToken);
    client.global.set("refreshToken",response.body.data.refreshToken);
    client.global.set("user_token",response.body.data.accessToken);
 %}

### 4. Login - happy path (ADMIN) → sets admin_token
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "{{adminEmail}}",
  "password": "admin123"
}

> {%
    client.global.set("admin_token", response.body.data.accessToken);
%}

### 5. Login - happy path (MANAGER) → sets manager_token
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "{{managerEmail}}",
  "password": "manager123"
}

> {%
    client.global.set("manager_token", response.body.data.accessToken);
%}


### 6.Login failure - Sad path - wrong password -400
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "{{studentEmail}}",
  "password": "123123123"
}

### ====== Protected endpoint access ======
### 7.Access user profile - happy path - with valid accessToken
GET {{host}}/api/v1/users/me
Authorization: Bearer {{accessToken}}

### 8.Access user profile - sad path - without token -401
GET {{host}}/api/v1/users/me

### 9.Access user profile - sad path - Replace accessToken with refreshToken -401
GET {{host}}/api/v1/users/me
Authorization: Bearer {{refreshToken}}

### ====== Refresh Token ======
### 10.RefreshToken - Happy path
POST {{host}}/api/v1/auth/refreshToken
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

> {%
 client.global.set("accessToken",response.body.data.accessToken);
 client.global.set("user_token",response.body.data.accessToken);
 %}

### 11.Refresh token failure - Sad path - invalid token type(access token)
POST {{host}}/api/v1/auth/refreshToken
Content-Type: application/json

{
  "refreshToken": "{{accessToken}}"
}

### 12.Refresh token failure - Sad path - refresh token is invalid->401
POST {{host}}/api/v1/auth/refreshToken
Content-Type: application/json

{
  "refreshToken": "invalid.refresh.token"
}

### ====== Logout ======
### 13.Logout - happy path
POST {{host}}/api/v1/auth/logout
Authorization: Bearer {{accessToken}}

### 14.Logout - sad path - logout without token ->401
POST {{host}}/api/v1/auth/logout

### 15.Refresh after logout - sad path → 400 (Redis key deleted)
POST {{host}}/api/v1/auth/refreshToken
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}




