package io.github.j_yuhanwang.food_ordering_app.auth_users.services;

import io.github.j_yuhanwang.food_ordering_app.auth_users.dtos.LoginRequest;
import io.github.j_yuhanwang.food_ordering_app.auth_users.dtos.LoginResponse;
import io.github.j_yuhanwang.food_ordering_app.auth_users.dtos.RegistrationRequest;
import io.github.j_yuhanwang.food_ordering_app.auth_users.dtos.UserDTO;
import io.github.j_yuhanwang.food_ordering_app.auth_users.entity.User;
import io.github.j_yuhanwang.food_ordering_app.auth_users.mapper.UserMapper;
import io.github.j_yuhanwang.food_ordering_app.auth_users.repository.UserRepository;
import io.github.j_yuhanwang.food_ordering_app.enums.RoleType;
import io.github.j_yuhanwang.food_ordering_app.enums.UserStatus;
import io.github.j_yuhanwang.food_ordering_app.exceptions.BadRequestException;
import io.github.j_yuhanwang.food_ordering_app.exceptions.ResourceNotFoundException;
import io.github.j_yuhanwang.food_ordering_app.exceptions.UserAlreadyExistsException;
import io.github.j_yuhanwang.food_ordering_app.security.JwtUtils;
import io.github.j_yuhanwang.food_ordering_app.security.RedisTokenService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Service implementation for user authentication and registration.
 *
 * @author YuhanWang
 * @Date 16/03/2026 11:41 am
 */
@Service
@Slf4j
@RequiredArgsConstructor
public class AuthServiceImpl implements AuthService {
    /**
     * The input username and password are encapsulated into an authentication object.
     * The input password is encrypted using passwordEncoder and compared with the password of the user in the userrepository database.
     * If the comparison is successful, a string generated by jwtUtils is returned.
     */
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder; //matches & encode,stored the encoded password in the database
    private final JwtUtils jwtUtils;
    private final UserMapper userMapper;
    private final RedisTokenService redisTokenService;

    @Override
    public UserDTO register(RegistrationRequest registrationRequest) {

        log.info("Attempting to register...");
        // 1. Check if email is already registered
        if (userRepository.existsByEmail(registrationRequest.getEmail())) {
            throw new UserAlreadyExistsException("Email already exists.");
        }

        // 2. Resolve user roles
        List<RoleType> userRoles;
        userRoles = registrationRequest.getRoles() != null
                && !registrationRequest.getRoles().isEmpty()
                ? registrationRequest.getRoles() : List.of(RoleType.ROLE_STUDENT);

        // 3. Encode password and build User entity
        String encodedPwd = passwordEncoder.encode(registrationRequest.getPassword());
        User newUser = User.builder()
                .name(registrationRequest.getName())
                .email(registrationRequest.getEmail())
                .address(registrationRequest.getAddress())
                .phoneNumber(registrationRequest.getPhoneNumber())
                .password(encodedPwd)
                .roles(userRoles)
                .build();

        // 4. Save user to database
        User savedUser = userRepository.save(newUser);
        // 5. Return sanitized UserDTO (excluding sensitive data like password)
        log.info("User registered successfully.");
        return userMapper.toDTO(savedUser);
    }

    @Override
    public void logout(String email) {
        log.info("Attempting to log out, cleaning up the refresh token");
        User user = userRepository.findByEmail(email)
                        .orElseThrow(()->new ResourceNotFoundException("User","email",email));
        redisTokenService.deleteRefreshToken(user.getId());
    }

    @Override
    public LoginResponse login(LoginRequest loginRequest) {
        log.info("Attempting to login");
        // 1. Fetch user by email
        User user = userRepository.findByEmail(loginRequest.getEmail())
                .orElseThrow(() -> new BadRequestException("Invalid email or password"));
        // 2. Verify password match
        if (!passwordEncoder.matches(loginRequest.getPassword(), user.getPassword())) {
            throw new BadRequestException("Invalid email or password");
        }

        // 3. Check if account is active
        if (user.getUserStatus() != UserStatus.ACTIVE) {
            throw new AccessDeniedException("Account is not active. Please contact customer support.");
        }
        // 4. Generate dual tokens
        List<RoleType> roles = user.getRoles();
        String accessToken = jwtUtils.generateAccessToken(user.getEmail(),roles);
        String refreshToken = jwtUtils.generateRefreshToken(user.getEmail());

        // 5. Store refresh token in Redis
        redisTokenService.saveRefreshToken(user.getId(),refreshToken);

        // 6. Build and return response
        return LoginResponse.builder()
                .accessToken(accessToken)
                .refreshToken(refreshToken)
                .roles(roles)
                .build();
    }

    @Override
    public LoginResponse refreshToken(String refreshToken) {
        log.info("Attempting to refresh token");
        // 1. Validate JWT signature and expiry (throws exception if invalid)
        String tokenType = jwtUtils.extractTokenType(refreshToken);
        if(!"refresh".equals(tokenType)){
            throw new BadRequestException("Invalid token type");
        }

        // 2. Get email from token, find user in DB
        String email = jwtUtils.getUsernameFromToken(refreshToken);
        User user = userRepository.findByEmail(email)
                .orElseThrow(()-> new ResourceNotFoundException("User","email",email));

        // 3. Validate against Redis — confirms session hasn't been revoked
        if(!redisTokenService.isRefreshTokenValid(user.getId(),refreshToken)){
            throw new BadRequestException("Refresh token is invalid or has been revoked");
        }

        // 4. Fetch latest roles from DB and generate new access token
        String newAccessToken = jwtUtils.generateAccessToken(email,user.getRoles());
        return LoginResponse.builder()
                .accessToken(newAccessToken)
                .build();
    }
}
